FROM golang:1.25-alpine AS builder
WORKDIR /app

RUN apk add --no-cache air gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/bin/server ./cmd/main.go

FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/bin/server /app/server
COPY --from=builder /app/.air.toml /app/.air.toml 2>/dev/null || true

EXPOSE 8080

CMD ["air"]
